apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/minio-data/minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/minio-data/postgres
